// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVKqADdrt5kguwuiAPrnDo4fSDmm4JLwU',
    appId: '1:953913671867:web:052c3977ed3c2566d3e99e',
    messagingSenderId: '953913671867',
    projectId: 'efficials-v2',
    authDomain: 'efficials-v2.firebaseapp.com',
    storageBucket: 'efficials-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyM2eWgRF3jMtc4QY-Nio0YBfv-N6wvIw',
    appId: '1:953913671867:android:9fb3bab39308df72d3e99e',
    messagingSenderId: '953913671867',
    projectId: 'efficials-v2',
    storageBucket: 'efficials-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_NfO4C_-YGT-Rke1WAe6M415KvRKcF34',
    appId: '1:953913671867:ios:8be7dbc95f378749d3e99e',
    messagingSenderId: '953913671867',
    projectId: 'efficials-v2',
    storageBucket: 'efficials-v2.firebasestorage.app',
    iosBundleId: 'com.example.efficialsV2',
  );
}
